_BOOTSTRAP_SERVER: "http://127.0.0.1:9092"
_CLIENT_ID: "user-service"
_CLIENT_SECRET: Rle6yJmeQ047gIJfxLDIMwDbto6ymUgI
_DATASOURCE_PASSWORD: "postgres"
_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/users"
_DATASOURCE_USERNAME: "postgres"
_HOSTNAME: "localhost"
_ISSUER_URI: "http://localhost:8080/realms/ICMSS"
_JWK_SET_URI: http://localhost:8080/realms/ICMSS/protocol/openid-connect/certs
_KEYCLOAK_URI: "http://localhost:8080/"
_MAIL_PASSWORD: "hejrxqfjlthbstvq"
_MAIL_USERNAME: "smartride6@gmail.com"
_REDIRECT_URI: "http://localhost:9010/authorized"
_REDIS_HOST: "localhost"
_REDIS_PORT: 6379
_SERVICE_URL_DEFAULT_ZONE: "http://localhost:9001/eureka"
_TOKEN_URI: "http://localhost:8080/realms/PoputkaAPP/protocol/openid-connect/token"
_SWAGGER_SERVER_URL: http://localhost:9003/user-microservice
_GATEWAY_NAME: "gateway"
